name: 'Auto label'
description: 'issue creator can check their own labels'
author: 'Renato66'
icon: 'check-square'
color: 'blue'
inputs: 
  repo-token:
    description: 'github token for the repository'
    required: true
  allow-create:
    descriptioin: 'allow label creation'
    defaul: false
  is-hidden:
    descriptioin: 'Are checkboxes inside a comentary block?'
    defaul: false
runs:
  using: 'docker'
  image: 'Dockerfile'