name: 'Container Action Template'
description: 'Get started with Container actions'
author: 'GitHub'
inputs: 
  repo-token:
    description: 'github token for the repository'
    required: true
  allow-create:
    descriptioin: 'allow label creation'
    defaul: false
  is-hidden:
    descriptioin: 'Are checkboxes inside a comentary block?'
    defaul: false
runs:
  using: 'docker'
  image: 'Dockerfile'