name: 'Auto label'
description: 'issue creator can check their own labels'
author: 'Renato66'
branding:
  icon: 'check-square'
  color: 'blue'
inputs: 
  repo-token:
    description: 'github token for the repository'
    required: true
  ignore-comments:
    descriptioin: 'ignore labels inside comments'
    defaul: true
runs:
  using: 'docker'
  image: 'Dockerfile'