name: Labeling new issue

on:
  issues:
      types: ['opened']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github/workflows/auto-label.json
          sparse-checkout-cone-mode: false
      - uses: Renato66/auto-label@main
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
