name: Deploy to GitHub Pages
on:
  push:
    branches:
      - front
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install modules
      run:
        yarn
    - name: Build
      run:
        yarn build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: front
        BRANCH: gh-pages
        FOLDER: dist
